// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp1NLuX36b_frf11WvijRUtqG-B7oojuc',
    appId: '1:388275914892:web:494f638dbeb4e4689253a9',
    messagingSenderId: '388275914892',
    projectId: 'ecomapp-89fd9',
    authDomain: 'ecomapp-89fd9.firebaseapp.com',
    storageBucket: 'ecomapp-89fd9.appspot.com',
    measurementId: 'G-W7E6150P7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-wXZGQTnJ_zlrip02Mjx6R4bCMaLiD-k',
    appId: '1:388275914892:android:16c8b44b38a7e06c9253a9',
    messagingSenderId: '388275914892',
    projectId: 'ecomapp-89fd9',
    storageBucket: 'ecomapp-89fd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2sLjwwZLHpIq2j-cBqALpeOx-yuxRavs',
    appId: '1:388275914892:ios:9ebc0bfbc81bfce89253a9',
    messagingSenderId: '388275914892',
    projectId: 'ecomapp-89fd9',
    storageBucket: 'ecomapp-89fd9.appspot.com',
    iosClientId: '388275914892-0651ufkngnqd769rokvi4a2ahjuh6568.apps.googleusercontent.com',
    iosBundleId: 'com.ecomapp.lmn',
  );
}
